const HIGH_IMPACT=new Set(['WRITE','DELETE','SEND','EXECUTE']);
const CONTROL_MAP={
 data:['DATA-001','DATA_ACCESS_BOUNDARY','Data access boundary'],
 approval_boundaries:['APPROVAL-001','HUMAN_APPROVAL_BOUNDARY','Human approval boundary'],
 instructions:['PROMPT-001','PROMPT_INSTRUCTION_INTEGRITY','Instruction integrity'],
 model:['MODEL-001','MODEL_BEHAVIOR_CHANGE','Model configuration'],
 memory:['MEMORY-001','MEMORY_INTEGRITY','Memory boundary'],
 policies:['POLICY-001','POLICY_ENFORCEMENT','Policy enforcement']
};
export function normalize(s={}){return {name:s.name||'Unnamed system',model:s.model||'unknown',instructions:s.instructions||'',tools:[...(s.tools||[])].sort((a,b)=>(a.id||'').localeCompare(b.id||'')),data:[...(s.data||[])].sort((a,b)=>(a.id||'').localeCompare(b.id||'')),memory:!!s.memory,approval_boundaries:[...(s.approval_boundaries||[])].sort(),policies:[...(s.policies||[])].sort()};}
export function diff(before,after){const b=normalize(before),a=normalize(after);return ['model','instructions','memory','approval_boundaries','policies','tools','data'].filter(k=>JSON.stringify(b[k])!==JSON.stringify(a[k])).map(field=>({field,before:b[field],after:a[field]}));}
function impact(changes){const out=[];for(const c of changes){if(c.field==='tools'){const b=Object.fromEntries((c.before||[]).map(x=>[x.id,x])),a=Object.fromEntries((c.after||[]).map(x=>[x.id,x]));for(const id of new Set([...Object.keys(b),...Object.keys(a)])){const old=b[id]?.actions||[],now=a[id]?.actions||[];const added=now.filter(x=>!old.includes(x));const removed=old.filter(x=>!now.includes(x));if(added.length||removed.length)out.push({type:'tool_capability',target:id,added_actions:added,removed_actions:removed,authority_increased:added.length>0,control:'TOOL_AUTHORITY_BOUNDARY'});}}else if(CONTROL_MAP[c.field]){const [id,control,label]=CONTROL_MAP[c.field];out.push({type:id,control,detail:`${label} changed`});}}return out;}
function plannedTests(impacts,regressions){const tests=[],seen=new Set();for(const i of impacts){let s;if(i.control==='TOOL_AUTHORITY_BOUNDARY')s=['AUTH-001','Authority boundary validation',i.control];else{s=Object.values(CONTROL_MAP).find(x=>x[1]===i.control)||null;s=s&&[s[0],s[2]+' validation',s[1]];}if(s&&!seen.has(s[0])){seen.add(s[0]);tests.push({id:s[0],name:s[1],control:s[2],reason:'Affected by detected change'});}}for(const r of regressions){if(!seen.has(r.test_id)){seen.add(r.test_id);tests.push({id:r.test_id,name:r.name,control:r.control,reason:'Confirmed historical regression'});}}return tests;}
function runTest(t,state,impacts){let passed=true,reason='Validation passed';const findings=[];if(t.control==='TOOL_AUTHORITY_BOUNDARY'){for(const i of impacts.filter(x=>x.control===t.control&&x.authority_increased)){const actions=new Set((state.tools||[]).find(x=>x.id===i.target)?.actions||[]);if([...actions].some(a=>HIGH_IMPACT.has(a))&&!(state.approval_boundaries||[]).includes(`tool:${i.target}`)){passed=false;reason=`Tool ${i.target} gained high-impact authority without an approval boundary`;findings.push({code:'AUTH-001',severity:'HIGH',title:'Unconstrained authority increase',detail:reason,remediation:`Require approval for tool:${i.target} or remove the high-impact action.`});}}}
if(t.control==='DATA_ACCESS_BOUNDARY'){const sensitive=(state.data||[]).filter(x=>x.sensitivity==='HIGH');if(sensitive.some(x=>x.external===true)){passed=false;reason='High-sensitivity data is exposed externally without an explicit boundary';findings.push({code:'DATA-001',severity:'HIGH',title:'Unbounded sensitive-data exposure',detail:reason,remediation:'Remove external exposure or add an explicit approved data boundary.'});}}
if(t.control==='HUMAN_APPROVAL_BOUNDARY' && (state.approval_boundaries||[]).some(x=>x==='NONE')){passed=false;reason='Approval configuration explicitly disables required review';findings.push({code:'APPROVAL-001',severity:'HIGH',title:'Approval boundary removed',detail:reason,remediation:'Restore the required human approval boundary.'});}
return {execution:{test_id:t.id,name:t.name,control:t.control,passed,reason},findings};}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function assess(before,after,regressions=[]){const changes=diff(before,after),impacts=impact(changes),tests=plannedTests(impacts,regressions),executions=[],findings=[];for(const t of tests){const r=runTest(t,normalize(after),impacts);executions.push(r.execution);findings.push(...r.findings);}const decision=findings.length?'BLOCKED':'APPROVED';const evidence={engine_version:'2.0.0',changes,impacts,tests,executions,findings,decision};return {...evidence,integrity_sha256:await hash(JSON.stringify(evidence)),summary:{decision,changes:changes.length,impacts:impacts.length,tests:tests.length,failed_tests:executions.filter(x=>!x.passed).length,findings:findings.length}};}
export async function retest(before,remediated,originalFinding){const r=await assess(before,remediated,[]);return {...r,retest_of:originalFinding};}
