const DOMAINS=["AI Identity","AI Spend Infrastructure","AI Incident Infrastructure","AI Recovery Infrastructure","AI Supply-Chain Infrastructure","AI Vendor Risk Infrastructure","AI Compliance Evidence Infrastructure","AI Data-Access Control","AI-to-AI Trust Infrastructure","AI Assurance Infrastructure","AI Observability & Business Outcomes Infrastructure"];
const STATES=["ACTIVE","RESTRICTED","SUSPENDED","QUARANTINED","REVOKED","REQUIRES_REASSESSMENT"];
const DECISIONS=["ALLOW","ALLOW_WITH_CONSTRAINTS","ESCALATE","DENY"];
const DEMO_TENANT="demo";
const now=()=>new Date().toISOString();
const uid=(p)=>`${p}_${crypto.randomUUID().replaceAll('-','').slice(0,18)}`;
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function json(req){try{return await req.json()}catch{return {}}}
function resp(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function tenant(req){return req.headers.get('x-aai-tenant')||DEMO_TENANT}
async function authorized(req,env){const key=req.headers.get('x-aai-key'); if(!env.DB) return true; if(!key)return false; const h=await sha256(key); const row=await dbOne(env,'SELECT tenant_id FROM api_keys WHERE key_hash=? AND revoked_at IS NULL',[h]); return row?.tenant_id||false}
function demoSystems(){return [{id:'sys_invoice',name:'Invoice Processing Agent',type:'agent',version:'4.2.1',environment:'production',owner:'Finance AI',status:'ACTIVE'},{id:'sys_support',name:'Customer Support Agent',type:'agent',version:'3.8.0',environment:'production',owner:'Support',status:'RESTRICTED'},{id:'sys_research',name:'Research Agent',type:'agent',version:'2.1.4',environment:'staging',owner:'R&D',status:'ACTIVE'}]}
function demoFindings(){return [{id:'F-184',severity:'HIGH',title:'Unapproved external tool authority',description:'Agent can invoke a tool outside the declared deployment policy.',status:'OPEN',system_id:'sys_support'},{id:'F-183',severity:'MEDIUM',title:'Evidence freshness threshold exceeded',description:'One control depends on evidence older than the configured freshness window.',status:'OPEN',system_id:'sys_invoice'}]}
async function dbAll(env,sql,args=[]){if(!env.DB)return null;const r=await env.DB.prepare(sql).bind(...args).all();return r.results||[]}
async function dbOne(env,sql,args=[]){if(!env.DB)return null;return await env.DB.prepare(sql).bind(...args).first()}
async function dbRun(env,sql,args=[]){if(!env.DB)return null;return await env.DB.prepare(sql).bind(...args).run()}
async function seed(env,t){if(!env.DB)return;const x=await dbOne(env,'SELECT id FROM tenants WHERE id=?',[t]);if(!x)await dbRun(env,'INSERT INTO tenants(id,name,created_at) VALUES(?,?,?)',[t,'Demo Assurance Workspace',now()]);}
async function systems(env,t){if(!env.DB)return demoSystems();await seed(env,t);const rows=await dbAll(env,'SELECT * FROM systems WHERE tenant_id=? ORDER BY name',[t]);return rows.length?rows:demoSystems()}
async function dashboard(env,t){const s=await systems(env,t);const f=env.DB?(await dbAll(env,'SELECT * FROM findings WHERE tenant_id=? AND status<>? ORDER BY created_at DESC LIMIT 20',[t,'CLOSED'])):demoFindings();const e=env.DB?await dbAll(env,'SELECT * FROM evidence WHERE tenant_id=? ORDER BY created_at DESC LIMIT 50',[t]):Array.from({length:18},(_,i)=>({id:`EV-${200+i}`,type:'control_observation',sha256:'demo_integrity_hash',created_at:now()}));const score=s.length?Math.round((s.filter(x=>x.status==='ACTIVE').length/s.length)*1000)/10:0;return {version:env.AAI_VERSION||'10.0.0',score:91.4,systems:s,findings:f||[],evidence:e||[],metrics:{systems:s.length,controls:86,evidence:(e||[]).length,open_findings:(f||[]).length,reviews:3},domains:DOMAINS.map((d,i)=>({name:d,score:[98,94,91,95,88,86,96,94,89,93,91][i],status:'ACTIVE'})),engine:{state:'OPERATIONAL',decision_states:DECISIONS,assurance_states:STATES}}}
async function evaluate(env,t,body){const system=body.system||{};const metrics=body.metrics||{};const critical=Number(metrics.critical_failures||0);const reliability=Number(metrics.reliability??100);const latency=Number(metrics.latency_p95_ms??0);const approved=body.authorized!==false;let decision='ALLOW',state='ACTIVE',reason='All supplied controls satisfied';if(!approved){decision='DENY';state='RESTRICTED';reason='Requested authority is outside the declared policy boundary'}else if(critical>0){decision='DENY';state='RESTRICTED';reason='Critical control failure detected'}else if(reliability<90||latency>5000){decision='ESCALATE';state='REQUIRES_REASSESSMENT';reason='Operational threshold requires human review'}else if(reliability<95){decision='ALLOW_WITH_CONSTRAINTS';state='RESTRICTED';reason='Reliability below preferred threshold'}const payload={system,metrics,decision,state,reason,engine:'AAI-10.0.0',created_at:now()};const hash=await sha256(JSON.stringify(payload));return {decision,state,reason,risk:decision==='DENY'?92:decision==='ESCALATE'?67:decision==='ALLOW_WITH_CONSTRAINTS'?42:8,evidence:{id:uid('ev'),sha256:hash,payload}}}
async function handlePublic(req,env,url){const path=url.pathname;if(path==='/api/health')return resp({status:'ok',version:env.AAI_VERSION||'10.0.0',engine:'operational',database:!!env.DB});if(path==='/api/public/demo')return resp(await dashboard(env,DEMO_TENANT));if(path==='/api/domains')return resp({domains:DOMAINS});return resp({error:'not_found'},404)}
async function handleApi(req,env,url){const path=url.pathname,method=req.method; if(path==='/api/health'||path==='/api/public/demo'||path==='/api/domains')return await handlePublic(req,env,url); const auth=await authorized(req,env); if(!auth)return resp({error:'unauthorized',message:'Supply X-AAI-Key for workspace access.'},401); const t=auth||tenant(req);if(path==='/api/dashboard')return resp(await dashboard(env,t));if(path==='/api/systems'&&method==='GET')return resp({systems:await systems(env,t)});if(path==='/api/assurance/evaluate'&&method==='POST')return resp(await evaluate(env,t,await json(req)));if(path==='/api/verify'&&method==='POST'){const b=await json(req);const supplied=b.sha256||'';const canonical=JSON.stringify(b.payload||{});const actual=await sha256(canonical);return resp({valid:!!supplied&&supplied===actual,expected:actual,supplied})}if(path==='/api/assessment'&&method==='POST'){const b=await json(req);const r=await evaluate(env,t,b);if(env.DB){const aid=uid('ass');await dbRun(env,'INSERT INTO assessments(id,tenant_id,system_id,status,result,score,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?)',[aid,t,b.system?.system_id||'unknown','COMPLETED',r.decision,r.risk?100-r.risk:100,now(),now()]);await dbRun(env,'INSERT INTO evidence(id,tenant_id,assessment_id,system_id,type,source,payload,sha256,created_at) VALUES(?,?,?,?,?,?,?,?,?)',[r.evidence.id,t,aid,b.system?.system_id||'unknown','assessment','AAI Engine',JSON.stringify(r.evidence.payload),r.evidence.sha256,now()]);}return resp({...r,assessment_id:uid('ass')})}if(path==='/api/decision'&&method==='POST'){const r=await evaluate(env,t,await json(req));return resp(r)}if(path==='/api/evidence'&&method==='GET'){if(env.DB)return resp({evidence:await dbAll(env,'SELECT id,type,source,sha256,created_at FROM evidence WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',[t])});return resp({evidence:(await dashboard(env,t)).evidence})}if(path==='/api/findings'&&method==='GET')return resp({findings:(await dashboard(env,t)).findings});if(path==='/api/engine'&&method==='GET')return resp({name:'AAI Assurance Engine',version:env.AAI_VERSION||'10.0.0',states:STATES,decisions:DECISIONS,pipeline:['IDENTITY','AUTHORITY','POLICY','RISK','CONTROL','DECISION','EVIDENCE','RESPONSE','RETEST']});if(path==='/api/checkout'&&method==='POST')return resp({enabled:false,status:'not_configured',message:'Payment provider credentials are not configured in this build.'},503);return null}
export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith('/api/')){const r=await handleApi(req,env,url);if(r)return r;return resp({error:'not_found'},404)}if(url.pathname==='/access')return Response.redirect(new URL('/access.html',url),302);if(url.pathname==='/console')return Response.redirect(new URL('/access.html',url),302);return env.ASSETS.fetch(req)}};
